/*
Problem Statement:
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"


*/

// Driver code:
import java.util.HashMap;
import java.util.Scanner;

public class FindDifferenceOfTwoString {
	public static void main(String[] args) {
		Scanner scn = new Scanner(System.in);
		String s = scn.next();
		String t = scn.next();
		System.out.println(findTheDifference(s,t));
	}
	
	public static char findTheDifference(String s, String t) {
        HashMap<Character,Integer> map = new HashMap<>();
        char ans=t.charAt(0);
        
        for(int i=0;i<s.length();i++){
            if(map.containsKey(s.charAt(i))){
                map.put(s.charAt(i),map.get(s.charAt(i))+1);
            }else{
                map.put(s.charAt(i),1);
            }
        }
        
        for(int i=0;i<t.length();i++){
            if(map.containsKey(t.charAt(i))){
                if(map.get(t.charAt(i))<=0){
                    ans=t.charAt(i);
                    break;
                }
                map.put(t.charAt(i),map.get(t.charAt(i))-1);
            }else{
                ans=t.charAt(i);
                return ans;
            }
        }
        return ans;
    }
}
